name: Sync Fork and Notify

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # you can run it manually using workflow_dispatch event

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v2
        with:
          repository: 'JMN09/opencommitNotification'
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
      - name: Add Upstream
        run: git remote add upstream https://github.com/di-sukharev/opencommit.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Checkout Master
        run: git checkout master

      - name: Check for Updates
        id: check_updates
        run: |
          git pull upstream master --allow-unrelated-histories
          echo "updates"

      - name: Send Notification
        if: steps.check_updates.outputs.updates
        run: echo "Hello"
